# Generated by Django 6.0.2 on 2026-02-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_type',
            field=models.CharField(choices=[('URBAN', 'Urban'), ('RURAL', 'Rural')], default='RURAL', max_length=10),
        ),
        migrations.AddField(
            model_name='office',
            name='taluka',
            field=models.ForeignKey(blank=True, help_text='For Rural', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.taluka'),
        ),
        migrations.AddField(
            model_name='office',
            name='village',
            field=models.ForeignKey(blank=True, help_text='For Rural', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.village'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='api.district')),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='city',
            field=models.ForeignKey(blank=True, help_text='For Urban', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.city'),
        ),
    ]
