# Generated by Django 6.0.2 on 2026-02-18 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_office_office_type_office_taluka_office_village_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='city',
        ),
        migrations.AddField(
            model_name='token',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.district'),
        ),
        migrations.AddField(
            model_name='token',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='rural_or_urban',
            field=models.CharField(choices=[('URBAN', 'Urban'), ('RURAL', 'Rural')], default='RURAL', max_length=10),
        ),
        migrations.AddField(
            model_name='token',
            name='taluka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.taluka'),
        ),
        migrations.AddField(
            model_name='token',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.village'),
        ),
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(help_text='District Code (e.g., GJ01)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.district'),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_type',
            field=models.CharField(choices=[('URBAN', 'Urban'), ('RURAL', 'Rural')], max_length=10),
        ),
        migrations.AlterField(
            model_name='office',
            name='taluka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.taluka'),
        ),
        migrations.AlterField(
            model_name='office',
            name='village',
            field=models.ForeignKey(blank=True, help_text='Required if Rural', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.village'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
