# Generated by Django 6.0.2 on 2026-02-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_office_city_token_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taluka',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='taluka',
            unique_together={('name', 'district')},
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together={('name', 'taluka')},
        ),
    ]
