# Generated by Django 6.0.2 on 2026-02-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_taluka_options_alter_village_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_code',
            field=models.CharField(help_text='Unique Office Code', max_length=50, unique=True),
        ),
    ]
