# Generated by Django 6.0.2 on 2026-02-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_office_office_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('office_type', models.CharField(max_length=10)),
                ('avg_time_minutes', models.IntegerField(default=15, help_text='Average time in minutes')),
            ],
        ),
        migrations.AlterField(
            model_name='office',
            name='office_type',
            field=models.CharField(choices=[('URBAN', 'Urban'), ('RURAL', 'Rural'), ('RTO', 'Regional Transport Office')], max_length=10),
        ),
    ]
