# Generated by Django 6.0.2 on 2026-02-18 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_service_alter_office_office_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service'),
        ),
    ]
