# Generated by Django 6.0.2 on 2026-02-18 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_token_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='rto_code',
            field=models.CharField(blank=True, help_text='RTO Code (e.g., 01 for Ahmedabad)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='token_sequence_code',
            field=models.CharField(default='A', help_text='Code for token generation (e.g., A, B)', max_length=2),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['token_number'], name='api_token_token_n_fb5ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['office', 'created_at'], name='api_token_office__4f884c_idx'),
        ),
    ]
