# Generated by Django 6.0.2 on 2026-03-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_district_rto_code_office_token_sequence_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='blockchain_tx',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='token_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
