# Generated by Django 6.0.2 on 2026-03-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='slot_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
