# Generated by Django 6.0.2 on 2026-04-03 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_token_booking_date_token_slot_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_district',
            field=models.ForeignKey(blank=True, help_text='For District-level view access', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.district'),
        ),
    ]
