# Generated by Django 6.0.2 on 2026-04-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_token_verified_at_token_verified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_hash',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
